version: '3'

services:
  php_app:
    build: php-image/build
    container_name: php_app
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_NAME: test_db    
    restart: on-failure:3
    volumes:
      - ./src:/var/www/html
    networks:
      - test_network
    depends_on:
      - mysql            

  nginx:
    image: nginx:alpine3.18
    ports:
    - "8080:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./src:/var/www/html
    restart: always
    depends_on:
      - php_app
    networks:
      - test_network        

  mysql:
    image: mysql:8.0.36-debian
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always  
    networks:
      - test_network    


networks:
  test_network:
    driver: bridge      

volumes:
  mysql-data:
